version: '3'
services:
  redis:
    image: redis:4-alpine

  socket-server:
    image: golang:1.10-alpine
    command: go run main.go client.go hub.go updater.go reader.go
    working_dir: /go/src/app
    depends_on:
      - redis
    volumes:
      - ./socket-server:/go/src/app

  front:
    build: ./front
    command: middleman server -p 80 --bind-address 0.0.0.0
    volumes:
      - ./front:/app

  updater:
    build: ./updater
    command: ruby app.rb
    volumes:
      - ./updater:/app
    depends_on:
      - redis
    environment:
      - LOGGER_LEVEL

  balancer:
    image: nginx:1.15-alpine
    ports:
      - "8081:80"
    depends_on:
      - front
      - socket-server
    volumes:
      - ./balancer/nginx.conf:/etc/nginx/nginx.conf
