version: '3'
services:
  redis:
    image: redis:4-alpine
    restart: always

  socket-server:
    build: ./socket-server
    command: ./main
    restart: always
    links:
      - redis

  front:
    image: nginx:1.15-alpine
    restart: always
    volumes:
      - ./front/build:/usr/share/nginx/html

  updater:
    build: ./updater
    command: ruby app.rb
    links:
      - redis

  balancer:
    image: nginx:1.15-alpine
    ports:
      - "8081:80"
    links:
      - front
      - socket-server
    volumes:
      - ./balancer/nginx.conf:/etc/nginx/nginx.conf
