version: '2'
services:
  redis:
    image: redis:4-alpine

  socket-server:
    image: zaitsev/dzen-socket
    command: /app/app
    depends_on:
      - redis

  front:
    image: nginx:1.15-alpine
    volumes:
      - ./front/build:/usr/share/nginx/html

  updater:
    image: zaitsev/dzen-updater
    command: ruby app.rb
    volumes:
      - ./updater:/app
    depends_on:
      - redis
    environment:
      - LOGGER_LEVEL

  balancer:
    image: nginx:1.15-alpine
    ports:
      - "8081:80"
    depends_on:
      - front
      - socket-server
    volumes:
      - ./balancer/nginx.conf:/etc/nginx/nginx.conf
