version: '2'
services:
  redis:
    image: redis:4-alpine

  socket-server:
    image: zaitsev/dzen-socket-server
    command: /app/app
    depends_on:
      - redis

  front:
    image: zaitsev/dzen-front

  updater:
    image: zaitsev/dzen-updater
    command: ruby app.rb
    depends_on:
      - redis

  balancer:
    image:  zaitsev/dzen-balancer
    ports:
      - "8081:80"
    depends_on:
      - front
      - socket-server
